# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/solveit_client',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/solveit_client',
                'lib_path': 'solveit_client'},
  'syms': {'solveit_client.core': {'solveit_client.core.foo': ('core.html#foo', 'solveit_client/core.py')}}}
