# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_cli_dup2.ipynb.

# %% auto #0
__all__ = ['msg_keys', 'sic_cli', 'sic']

# %% ../nbs/01_cli_dup2.ipynb #a218f9d9
def sic_cli(a):
    op, pos, kw = _parse_args(a)
    if not op: return 'Usage: sic <operation> [args]\n\n' + '\n'.join([ f" {nm:10s} {cls.__doc__}"
                                                                        for nm, cls in _ns_map.items()])
    obj, kw = _resolve(op, kw)
    if obj in _ns_map.values():
        mems = L(inspect.getmembers(obj, lambda x: callable(x) or isinstance(x, property))).filter(lambda x: not x[0].startswith('_'))
        lines = [f"  {name:15s} {func.__doc__ or ''}" for name, func in mems]
        return f'Usage: sic {op}.<method> [args]\n\n' + '\n'.join(lines)
    if 'help' in kw:
        kw.pop('help')
        doc = obj.__doc__ or ''
        lines = [doc, '']
        if callable(obj):
            for k, v in docments(obj).items():
                if k in ('self', 'return'): continue
                lines.append(f"  --{k:20s} {v or ''}")
        return '\n'.join(lines)
    res = obj(*pos, **kw) if callable(obj) else obj
    return _to_json(res)

# %% ../nbs/01_cli_dup2.ipynb #eab98dc9
def _resolve(op, kws):
    parts = op.split('.')
    nm = parts[0]
    mthd = parts[1] if len(parts) > 1 else None
    if not mthd: return _ns_map[nm], kws
    url = kws.pop('url', os.environ.get('SOLVEIT_URL', 'http://localhost:5001'))
    tok = kws.pop('token', os.environ.get('SOLVEIT_TOKEN', ''))
    sic = SolveItClient(url, tok)
    if nm=='client': obj = sic
    else:
        dlg = Dialog(kws.pop('name', os.environ.get('SOLVEIT_DIALOG')), sic)
        if   nm=='dialog': obj = dlg
        elif nm=='message': obj= Message(kws.pop('id'), dlg)
        else: raise ValueError(f'Unknown object type {nm}')
    if mthd not in dir(obj): raise AttributeError(f"'{nm}' has no method '{mthd}'")
    attr = getattr(type(obj), mthd, None) if 'help' in kws else getattr(obj, mthd)
    return attr, kws

# %% ../nbs/01_cli_dup2.ipynb #34148642
def sic():
    "SolveIt CLI"
    print(sic_cli(sys.argv))

# %% ../nbs/01_cli_dup2.ipynb #10bb1402
from fastcore.docments import *
from fastcore.script import *
from fastcore.utils import *
from .core import *

import inspect,json,sys

# %% ../nbs/01_cli_dup2.ipynb #c49970a9
def _parse_args(a):
    "Extract positional and keyword arguments from `a`=`sys.argv`"
    pos,kw = [],{}
    if len(a)<2: return None,pos,kw
    i=1
    while i<len(a):
        x = a[i]
        if x[:2]=='--':
            k = x[2:]
            if k in ('help','debug'): y = 1
            else:
                i += 1
                y = a[i]
            kw[k] = y
        else: pos.append(a[i])
        i += 1
    a = pos.pop(0) if pos else None
    return a,pos,kw

# %% ../nbs/01_cli_dup2.ipynb #cf7e2638
_ns_map = {'client': SolveItClient, 'dialog': Dialog, 'message': Message}

def _pick(d, ks): return {k: d[k] for k in ks if k in d}
msg_keys = ['id','msg_type','content','output']
def _to_json(res):
    if isinstance(res, Dialog): res = _pick(res.data, ['name','mode'])
    elif isinstance(res, Messages): res = [_pick(m.data, msg_keys) for m in res]
    elif isinstance(res, MsgDiff): res = {**_pick(res.msg.data, msg_keys), 'diff': res.diff}
    elif hasattr(res, 'data'): res = _pick(res.data, msg_keys)
    return json.dumps(res, default=str)

# %% ../nbs/01_cli_dup2.ipynb #1454e3d4
def _resolve(op, kws):
    parts = op.split('.')
    nm = parts[0]
    mthd = parts[1] if len(parts) > 1 else None
    if not mthd: return _ns_map[nm], kws
    elif mthd and 'help' in kws:
        cls = _ns_map[nm]
        if mthd not in dir(cls): raise AttributeError(f"'{nm}' has no method '{mthd}'")
        return getattr(cls, mthd), kws
    url = kws.pop('url', os.environ.get('SOLVEIT_URL', 'http://localhost:5001'))
    tok = kws.pop('token', os.environ.get('SOLVEIT_TOKEN', ''))
    sic = SolveItClient(url, tok)
    if nm=='client': obj = sic
    else:
        dlg = Dialog(kws.pop('name', os.environ.get('SOLVEIT_DIALOG')), sic)
        if   nm=='dialog': obj = dlg
        elif nm=='message': obj= Message(kws.pop('id'), dlg)
        else: raise ValueError(f'Unknown object type {nm}')
    if mthd not in dir(obj): raise AttributeError(f"'{nm}' has no method '{mthd}'")
    attr = getattr(type(obj), mthd, None) if 'help' in kws else getattr(obj, mthd)
    return attr, kws

# %% ../nbs/01_cli_dup2.ipynb #3531ff50
def sic_cli(a):
    op, pos, kw = _parse_args(a)
    if not op: return 'Usage: sic <operation> [args]\n\n' + '\n'.join([ f" {nm:10s} {cls.__doc__}"
                                                                        for nm, cls in _ns_map.items()])
    obj, kw = _resolve(op, kw)
    if obj in _ns_map.values():
        mems = L(inspect.getmembers(obj, lambda x: callable(x) or isinstance(x, property))).filter(lambda x: not x[0].startswith('_'))
        lines = [f"  {name:15s} {func.__doc__ or ''}" for name, func in mems]
        return f'Usage: sic {op}.<method> [args]\n\n' + '\n'.join(lines)
    if 'help' in kw:
        kw.pop('help')
        doc = obj.__doc__ or ''
        lines = [doc, '']
        if callable(obj):
            for k, v in docments(obj).items():
                if k in ('self', 'return'): continue
                lines.append(f"  --{k:20s} {v or ''}")
        return '\n'.join(lines)
    res = obj(*pos, **kw) if callable(obj) else obj
    return _to_json(res)

# %% ../nbs/01_cli_dup2.ipynb #3b4dda8e
def sic():
    "SolveIt CLI"
    print(sic_cli(sys.argv))
