# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_cli.ipynb.

# %% ../nbs/01_cli.ipynb #cli-imports
from __future__ import annotations

from typing import Any

from fastcore.all import *
from fastcore.script import *
from .core import *

import json, os, sys

# %% auto #0
__all__ = ['sic', 'completion_sic']

# %% ../nbs/01_cli.ipynb #cli-runtime-1
_MSG_TYPES = ('code', 'note', 'prompt', 'raw')
_PLACEMENTS = ('add_after', 'add_before', 'at_start', 'at_end')
_DIALOG_FIELDS = ('name', 'link', 'mode', 'error')
_MESSAGE_FIELDS = ('id', 'dlg_name', 'link', 'msg_type', 'content', 'output', 'time_run', 'error')
_STATE = SimpleNamespace(client=None, pretty=False, url='', token='')


def _global_options(
    url:str='',  # SolveIt base URL. Defaults to `SOLVEIT_URL` or `http://localhost:5001`.
    token:str='',  # SolveIt token. Defaults to `SOLVEIT_TOKEN`.
    pretty:Param('Pretty-print JSON output', store_true)=False,
): ...

# %% ../nbs/01_cli.ipynb #cli-runtime-2
def _serialize(o:Any):
    if isinstance(o, Dialog):
        data = dict(o.data or {})
        data['name'], data['link'] = o.name, o.link
        return {k: data[k] for k in _DIALOG_FIELDS if k in data}
    if isinstance(o, Message):
        data = dict(o.data or {})
        data['id'], data['dlg_name'], data['link'] = o.id, o.dlg.name, o.link
        return {k: data[k] for k in _MESSAGE_FIELDS if k in data}
    if isinstance(o, (Messages, list, tuple, L)): return [_serialize(x) for x in o]
    if isinstance(o, dict): return {k: _serialize(v) for k, v in o.items()}
    return o


def _dump(o:Any): return json.dumps(_serialize(o), sort_keys=True, indent=2 if _STATE.pretty else None)


def _parse_value(v:str):
    try: return json.loads(v)
    except json.JSONDecodeError: return v


def _parse_pairs(pairs:list[str]):
    res = {}
    for pair in pairs:
        if '=' not in pair: raise ValueError(f'Expected key=value pair: {pair}')
        k, v = pair.split('=', 1)
        res[k] = _parse_value(v)
    return res


def _norm_opt(s:str): return '--' + s[2:].replace('-', '_') if s.startswith('--') else s
def _disp_opt(s:str): return '--' + s[2:].replace('_', '-') if s.startswith('--') else s

# %% ../nbs/01_cli.ipynb #cli-runtime-3
def _set_state(url:str='', token:str='', pretty:bool=False):
    _STATE.client = None
    _STATE.pretty = pretty
    _STATE.url = url
    _STATE.token = token


def _resolve_config(url:str='', token:str=''):
    url = url or _STATE.url or os.getenv('SOLVEIT_URL') or 'http://localhost:5001'
    token = token or _STATE.token or os.getenv('SOLVEIT_TOKEN', '')
    if not token: raise ValueError('Missing SolveIt token. Pass `--token` or set `SOLVEIT_TOKEN`.')
    return url, token


def _client():
    if _STATE.client is None:
        url, token = _resolve_config()
        _STATE.client = SolveItClient(url, token=token)
    return _STATE.client


def _dialog(dlg_name:str): return Dialog(dlg_name, _client())
def _message(dlg_name:str, msg_id:str): return _dialog(dlg_name).read_msg(id=msg_id)
def _emit(res:Any): print(_dump(res))

# %% ../nbs/01_cli.ipynb #cli-dialog-export
def _dialog_create(
    dlg_name:str,  # Dialog name
):
    "Create a dialog."
    return _client().create_dialog(dlg_name)


def _dialog_delete(
    dlg_name:str,  # Dialog name
):
    "Delete a dialog."
    return _dialog(dlg_name).delete()


def _dialog_find(
    dlg_name:str,  # Dialog name
    re_pattern:str,  # Regex pattern to search for
    msg_type:Param('Optional message type filter', choices=_MSG_TYPES)=None,
):
    "Find messages in a dialog with a regex."
    kw = dict(msg_type=msg_type) if msg_type else {}
    return _dialog(dlg_name).find_msgs(re_pattern=re_pattern, **kw)


def _dialog_msgs(
    dlg_name:str,  # Dialog name
    msg_type:Param('Optional message type filter', choices=_MSG_TYPES)=None,
):
    "List dialog messages."
    return _dialog(dlg_name).find_msgs(**(dict(msg_type=msg_type) if msg_type else {}))


def _dialog_xml(
    dlg_name:str,  # Dialog name
    msg_type:Param('Optional message type filter', choices=_MSG_TYPES)=None,
    nums:bool=False,  # Include line numbers
    include_output:bool=False,  # Include output content
    trunc_out:bool=True,  # Truncate output in XML
    trunc_in:bool=False,  # Truncate input in XML
):
    "Render dialog messages as XML."
    return _dialog(dlg_name).to_xml(msg_type=msg_type, nums=nums, include_output=include_output, trunc_out=trunc_out, trunc_in=trunc_in)


def _dialog_stop(
    dlg_name:str,  # Dialog name
):
    "Stop the current run queue."
    return _dialog(dlg_name).stop()


def _dialog_reset(
    dlg_name:str,  # Dialog name
):
    "Reset dialog execution state."
    return _dialog(dlg_name).reset()


def _dialog_run_all(
    dlg_name:str,  # Dialog name
):
    "Queue all runnable messages."
    return _dialog(dlg_name).run_all()

# %% ../nbs/01_cli.ipynb #cli-msg-export-1
def _msg_add(
    dlg_name:str,  # Dialog name
    content:str,  # Message content
    msg_type:Param('Message type', choices=_MSG_TYPES)='code',
    placement:Param('Placement relative to `ref_id` or dialog', choices=_PLACEMENTS)='at_end',
    ref_id:str=None,  # Reference message id for relative placement
    heading_collapsed:int=0,  # Collapse heading section
    i_collapsed:int=0,  # Collapse input
    o_collapsed:int=0,  # Collapse output
):
    "Add a message."
    return _dialog(dlg_name).add_msg(content, msg_type=msg_type, placement=placement, id=ref_id,
        heading_collapsed=heading_collapsed, i_collapsed=i_collapsed, o_collapsed=o_collapsed)


def _msg_read(
    dlg_name:str,  # Dialog name
    msg_id:str=None,  # Message id
    n:int=0,  # Relative message offset when `msg_id` is not provided
):
    "Read a message by id or offset."
    return _dialog(dlg_name).read_msg(id=msg_id, n=n)


def _msg_exec(
    dlg_name:str,  # Dialog name
    msg_id:str,  # Message id
    timeout:int=30,  # Max seconds to wait
    poll_interval:float=0.2,  # Poll interval in seconds
):
    "Execute a message and return the refreshed message."
    msg = _message(dlg_name, msg_id)
    msg.exec(timeout=timeout, poll_interval=poll_interval)
    return msg


def _msg_update(
    dlg_name:str,  # Dialog name
    msg_id:str,  # Message id
    content:str=None,  # Updated content
    output:str=None,  # Updated output
    msg_type:Param('Updated message type', choices=_MSG_TYPES)=None,
):
    "Update a message."
    kw = {k: v for k, v in dict(content=content, output=output, msg_type=msg_type).items() if v is not None}
    if not kw: raise ValueError('Provide at least one of `--content`, `--output`, or `--msg-type`.')
    msg, diff = _message(dlg_name, msg_id).update(**kw)
    return {'message': msg, 'diff': diff}


def _msg_delete(
    dlg_name:str,  # Dialog name
    msg_id:str,  # Message id
):
    "Delete a message."
    _message(dlg_name, msg_id).delete()
    return dict(success=True, id=msg_id, dlg_name=dlg_name)

# %% ../nbs/01_cli.ipynb #cli-msg-export-2
def _msg_str_replace(
    dlg_name:str,  # Dialog name
    msg_id:str,  # Message id
    old_str:str,  # Exact string to replace
    new_str:str,  # Replacement string
):
    "Replace a unique string in a message."
    msg, diff = _message(dlg_name, msg_id).str_replace(old_str, new_str)
    return {'message': msg, 'diff': diff}


def _msg_insert_line(
    dlg_name:str,  # Dialog name
    msg_id:str,  # Message id
    insert_line:int,  # Zero-based insertion index
    new_str:str,  # New line content
):
    "Insert a line into a message."
    msg, diff = _message(dlg_name, msg_id).insert_line(insert_line, new_str)
    return {'message': msg, 'diff': diff}


def _msg_replace_lines(
    dlg_name:str,  # Dialog name
    msg_id:str,  # Message id
    start_line:int,  # One-based start line
    new_content:str,  # Replacement block
    end_line:int=None,  # Optional inclusive end line
):
    "Replace a line range in a message."
    msg, diff = _message(dlg_name, msg_id).replace_lines(start_line, end_line=end_line, new_content=new_content)
    return {'message': msg, 'diff': diff}


def _msg_del_lines(
    dlg_name:str,  # Dialog name
    msg_id:str,  # Message id
    start_line:int,  # One-based start line
    end_line:int=None,  # Optional inclusive end line
):
    "Delete a line range in a message."
    msg, diff = _message(dlg_name, msg_id).del_lines(start_line, end_line=end_line)
    return {'message': msg, 'diff': diff}

# %% ../nbs/01_cli.ipynb #cli-dispatch-export-1
def _raw(
    path:str,  # SolveIt route, e.g. `/find_msgs_`
    pairs:Param('Request data in key=value form', nargs='*', opt=False)=(),
):
    "Call a raw SolveIt route."
    return _client()(path, **_parse_pairs(list(pairs)))


_DIALOG_CMDS = {'create': _dialog_create, 'delete': _dialog_delete, 'find': _dialog_find,
    'msgs': _dialog_msgs, 'xml': _dialog_xml, 'stop': _dialog_stop, 'reset': _dialog_reset, 'run-all': _dialog_run_all}

_MSG_CMDS = dict(add=_msg_add, read=_msg_read, exec=_msg_exec, update=_msg_update, delete=_msg_delete) | {
    'str-replace': _msg_str_replace, 'insert-line': _msg_insert_line, 'replace-lines': _msg_replace_lines, 'del-lines': _msg_del_lines}

_GROUPS = {'dialog': _DIALOG_CMDS, 'msg': _MSG_CMDS}


def _usage(): return 'Usage: sic [--url URL] [--token TOKEN] [--pretty] <dialog|msg|raw> ...'


def _group_usage(name:str, cmds:dict):
    joined = '|'.join(cmds)
    return f'Usage: sic {name} <{joined}>'


def _parser(func, prog:str): return anno_parser(func, prog=prog)


def _call(func, argv:list[str], prog:str):
    args = _parser(func, prog).parse_args([_norm_opt(o) for o in argv]).__dict__
    args.pop('pdb', None)
    args.pop('xtra', None)
    return func(**args)


def _dispatch(group:str, argv:list[str]):
    cmds = _GROUPS[group]
    if not argv:
        print(_group_usage(group, cmds))
        return None
    cmd, rest = argv[0], argv[1:]
    if cmd not in cmds: raise ValueError(f'Unknown {group} command: {cmd}')
    return _call(cmds[cmd], rest, f'sic {group} {cmd}')

# %% ../nbs/01_cli.ipynb #cli-dispatch-export-2
def _option_strings(parser): return [_disp_opt(o) for a in parser._actions for o in a.option_strings if o not in ('--pdb', '--xtra')]


def _choices_for(parser, opt:str):
    opt = _norm_opt(opt)
    for action in parser._actions:
        if opt in action.option_strings and action.choices: return [str(o) for o in action.choices]
    return []


def _filter(opts:list[str], prefix:str):
    seen = []
    for o in opts:
        if o.startswith(prefix) and o not in seen: seen.append(o)
    return seen


def _complete(words:list[str]):
    current = words[-1] if words else ''
    prev = words[-2] if len(words) > 1 else ''
    global_opts = _option_strings(_parser(_global_options, 'sic'))
    if not words: return list(_GROUPS) + ['raw', *global_opts]
    head = words[0]
    if len(words) == 1 and head not in _GROUPS and head != 'raw' and not head.startswith('-'):
        return _filter([*list(_GROUPS), 'raw', *global_opts], head)
    if head.startswith('-'): return _filter(global_opts, current)
    if head in _GROUPS and len(words) == 2 and words[1] and not words[1].startswith('-'):
        return _filter(list(_GROUPS[head]), words[1])
    if head in _GROUPS and len(words) == 2: return _filter(list(_GROUPS[head]), current)
    if head in _GROUPS:
        cmd = words[1]
        if cmd not in _GROUPS[head]: return _filter(list(_GROUPS[head]), cmd)
        parser = _parser(_GROUPS[head][cmd], f'sic {head} {cmd}')
    elif head == 'raw': parser = _parser(_raw, 'sic raw')
    else: return []
    choices = _choices_for(parser, prev)
    if choices: return _filter(choices, current)
    return _filter(_option_strings(parser), current)


_TAB_COMPLETION = """
_do_sic_completions()
{
    local IFS=$'\\n'
    COMPREPLY=($(completion-sic "$COMP_CWORD" "${COMP_WORDS[@]:1}"))
}

complete -F _do_sic_completions sic
"""

# %% ../nbs/01_cli.ipynb #cli-entry-export
@call_parse(nested=True)
def sic(
    url:str='',  # SolveIt base URL. Defaults to `SOLVEIT_URL` or `http://localhost:5001`.
    token:str='',  # SolveIt token. Defaults to `SOLVEIT_TOKEN`.
    pretty:bool=False,  # Pretty-print JSON output
):
    "Python backend for the `sic` command."
    try:
        _set_state(url=url, token=token, pretty=pretty)
        rest = sys.argv[1:]
        if not rest:
            print(_usage())
            return
        head, rest = rest[0], rest[1:]
        if head in _GROUPS: res = _dispatch(head, rest)
        elif head == 'raw': res = _call(_raw, rest, 'sic raw')
        else: raise ValueError(f'Unknown command: {head}')
        if res is not None: _emit(res)
    except Exception as e: raise SystemExit(str(e)) from e


def completion_sic():
    "Python backend for `completion-sic`."
    if len(sys.argv) == 2 and sys.argv[1] == '--install':
        print(_TAB_COMPLETION)
        return
    cword = int(sys.argv[1]) if len(sys.argv) > 1 else 0
    words = sys.argv[2:]
    while len(words) <= cword: words.append('')
    print(' '.join(_complete(words[:cword + 1])))
