"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['SolveItClient', 'Dialog', 'Message', 'Messages']

# %% ../nbs/00_core.ipynb #9f0e6184
from fastcore.utils import *

import httpx, os, time

# %% ../nbs/00_core.ipynb #34184ad1
class SolveItClient:
    def __init__(self, url, token=None):
        self.url, self.token = url, token or os.environ['SOLVEIT_TOKEN']
        self.cli = httpx.Client(base_url=url, cookies={'_solveit': self.token}, headers={'Accept': 'application/json'})
    
    def __call__(self, path, **data):
        res = self.cli.post(path, data=data)
        try: return res.json()
        except: return res.text
    
    def __repr__(self): return f'SolveItClient({self.url=})'

# %% ../nbs/00_core.ipynb #bd1bbb3c
class Dialog:
    def __init__(self, name, cli):
        self.name, self.cli = name, cli
        self._refresh()
    
    def _refresh(self):
        self.data = self.cli('/curr_dialog_', dlg_name=self.name)
    
    def __getattr__(self, k): return self.data.get(k)
    def __getitem__(self, k): return self.data[k]
    def __dir__(self): return list(self.data.keys()) + dir(type(self))
    def __repr__(self): return f"Dialog('{self.name}', mode={self.mode})"
    @property
    def link(self): return f'{self.cli.url}dialog_?name={self.name}'
    def _repr_html_(self): 
        return f"<b>Dialog:</b> <a href='{self.link}' target='_blank'><code>{self.name}</code></a> | <b>Mode:</b> {self.mode}"

# %% ../nbs/00_core.ipynb #ddda7809
@patch
def create_dialog(self:SolveItClient, dlg_nm):
    self('/create_dialog_', name=dlg_nm, api=True)
    return Dialog(dlg_nm, self)

# %% ../nbs/00_core.ipynb #254216c9
class Message:
    def __init__(self, id, dlg, data=None):
        self.id, self.dlg = id, dlg
        self.data = data if data else self._refresh()
    
    def _refresh(self):
        self.data = self.dlg.cli('/read_msg_', dlg_name=self.dlg.name, id_=self.id, n=0, relative=True)
        return self.data
    
    def __getattr__(self, k): return self.data.get(k)
    def __getitem__(self, k): return self.data[k]
    def __dir__(self): return list(self.data.keys()) + dir(type(self))
    def __repr__(self): return f"Message('{self.id}', type={self.msg_type})"
    @property
    def link(self): return self.dlg.link + f'#{self.id}'
    def _repr_html_(self): 
        preview = (self.content[:50] + '...') if len(self.content or '') > 50 else self.content
        out = (self.output[:50] + '...') if len(self.output or '') > 50 else (self.output or '')
        return f"<b>Message:</b> <a href='{self.link}' target='_blank'><code>{self.id}</code></a> | <b>Type:</b> {self.msg_type} | <code>{preview}</code> | <b>Output:</b> <code>{out}</code>"

# %% ../nbs/00_core.ipynb #b0a4a828
class Messages(list):
    def __init__(self, msgs, dlg):
        super().__init__(Message(m['id'], dlg, m) for m in msgs)
    def _repr_html_(self):
        rows = ''.join(f"<tr><td><a href='{m.link}' target='_blank'><code>{m.id}</code></a></td><td>{m.msg_type}</td><td>{(m.content or '')[:40]}</td><td>{(m.output or '')[:40]}</td></tr>" for m in self)
        return f"<table style='border-collapse:collapse'><tr><th style='padding:4px 12px;text-align:left'>ID</th><th style='padding:4px 12px;text-align:left'>Type</th><th style='padding:4px 12px;text-align:left'>Content</th><th style='padding:4px 12px;text-align:left'>Output</th></tr>{rows.replace('<td>', '<td style=\"padding:4px 12px\">')}</table>"

# %% ../nbs/00_core.ipynb #e84bed01
@patch(as_prop=True)
def messages(self:Dialog):
    return Messages(self.cli('/find_msgs_', dlg_name=self.name)['msgs'], self)

# %% ../nbs/00_core.ipynb #5713ef88
@patch
def exec(self:Message, timeout=30, poll_interval=0.2):
    self.dlg.cli('/add_runq_', dlg_name=self.dlg.name, id_=self.id, api='true')
    for _ in range(int(timeout / poll_interval)):
        time.sleep(poll_interval)
        self._refresh()
        if not self.data.get('run'): break
    return self.output

# %% ../nbs/00_core.ipynb #ef26e312
@patch
def update(self:Message, **kwargs):
    if 'msg_type' in kwargs: kwargs.setdefault('output', '')
    self.dlg.cli('/update_msg_', dlg_name=self.dlg.name, id_=self.id, **kwargs)
    self._refresh()
    return self

# %% ../nbs/00_core.ipynb #7932f6d8
@patch
def delete(self:Message):
    self.dlg.cli('/rm_msg_', dlg_name=self.dlg.name, msid=self.id, api='true')
    return self

# %% ../nbs/00_core.ipynb #69999e1b
@patch
def stop(self:Dialog): self.cli('/stop_', dlg_name=self.name); return self

@patch
def reset(self:Dialog): self.cli('/reset_', dlg_name=self.name); return self

@patch
def run_all(self:Dialog): self.cli('/run_all_', dlg_name=self.name); return self

# %% ../nbs/00_core.ipynb #dceb0354
@patch
def delete(self:Dialog): return self.cli('/rm_dialog_', name=self.name, api='true')
